# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hatchers-frontend' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'
  pod 'Bolts'

# Your 'node_modules' directory is probably in the root of your project,
# but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
   	'Core',
	'CxxBridge',
	'RCTNetwork',
	'RCTText',
	'RCTWebSocket', # needed for debugging
	'RCTAnimation',
   	'DevSupport',
	'RCTImage'
 ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

	post_install do |installer|
	  installer.pods_project.targets.each do |target|
	    if target.name == "React"
	      target.remove_from_project
	    end
	  end
	end
end
